/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ch.dvbern.kibon.exchange.commons.tagesschulen;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ModulDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3423667257194718413L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ModulDTO\",\"namespace\":\"ch.dvbern.kibon.exchange.commons.tagesschulen\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bezeichnungDE\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"bezeichnungFR\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"zeitVon\",\"type\":{\"type\":\"long\",\"logicalType\":\"time-millis\"}},{\"name\":\"zeitBis\",\"type\":{\"type\":\"long\",\"logicalType\":\"time-millis\"}},{\"name\":\"wochentage\",\"type\":{\"type\":\"array\",\"items\":\"int\",\"java-class\":\"java.util.List\"}},{\"name\":\"intervall\",\"type\":{\"type\":\"enum\",\"name\":\"Intervall\",\"namespace\":\"ch.dvbern.kibon.exchange.commons.types\",\"symbols\":[\"WOECHENTLICH\",\"ALLE_ZWEI_WOCHEN\"]}},{\"name\":\"padaegogischBetreut\",\"type\":\"boolean\"},{\"name\":\"verpflegungsKosten\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":2}},{\"name\":\"gesuchsperiode\",\"type\":{\"type\":\"record\",\"name\":\"Gesuchsperiode\",\"namespace\":\"ch.dvbern.kibon.exchange.commons.types\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"gueltigAb\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}},{\"name\":\"gueltigBis\",\"type\":{\"type\":\"int\",\"logicalType\":\"date\"}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<ModulDTO> ENCODER =
      new BinaryMessageEncoder<ModulDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ModulDTO> DECODER =
      new BinaryMessageDecoder<ModulDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ModulDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ModulDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ModulDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ModulDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ModulDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ModulDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ModulDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ModulDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String id;
   private java.lang.String bezeichnungDE;
   private java.lang.String bezeichnungFR;
   private long zeitVon;
   private long zeitBis;
   private java.util.List<java.lang.Integer> wochentage;
   private ch.dvbern.kibon.exchange.commons.types.Intervall intervall;
   private boolean padaegogischBetreut;
   private java.math.BigDecimal verpflegungsKosten;
   private ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode gesuchsperiode;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ModulDTO() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param bezeichnungDE The new value for bezeichnungDE
   * @param bezeichnungFR The new value for bezeichnungFR
   * @param zeitVon The new value for zeitVon
   * @param zeitBis The new value for zeitBis
   * @param wochentage The new value for wochentage
   * @param intervall The new value for intervall
   * @param padaegogischBetreut The new value for padaegogischBetreut
   * @param verpflegungsKosten The new value for verpflegungsKosten
   * @param gesuchsperiode The new value for gesuchsperiode
   */
  public ModulDTO(java.lang.String id, java.lang.String bezeichnungDE, java.lang.String bezeichnungFR, java.lang.Long zeitVon, java.lang.Long zeitBis, java.util.List<java.lang.Integer> wochentage, ch.dvbern.kibon.exchange.commons.types.Intervall intervall, java.lang.Boolean padaegogischBetreut, java.math.BigDecimal verpflegungsKosten, ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode gesuchsperiode) {
    this.id = id;
    this.bezeichnungDE = bezeichnungDE;
    this.bezeichnungFR = bezeichnungFR;
    this.zeitVon = zeitVon;
    this.zeitBis = zeitBis;
    this.wochentage = wochentage;
    this.intervall = intervall;
    this.padaegogischBetreut = padaegogischBetreut;
    this.verpflegungsKosten = verpflegungsKosten;
    this.gesuchsperiode = gesuchsperiode;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return bezeichnungDE;
    case 2: return bezeichnungFR;
    case 3: return zeitVon;
    case 4: return zeitBis;
    case 5: return wochentage;
    case 6: return intervall;
    case 7: return padaegogischBetreut;
    case 8: return verpflegungsKosten;
    case 9: return gesuchsperiode;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: bezeichnungDE = value$ != null ? value$.toString() : null; break;
    case 2: bezeichnungFR = value$ != null ? value$.toString() : null; break;
    case 3: zeitVon = (java.lang.Long)value$; break;
    case 4: zeitBis = (java.lang.Long)value$; break;
    case 5: wochentage = (java.util.List<java.lang.Integer>)value$; break;
    case 6: intervall = (ch.dvbern.kibon.exchange.commons.types.Intervall)value$; break;
    case 7: padaegogischBetreut = (java.lang.Boolean)value$; break;
    case 8: verpflegungsKosten = (java.math.BigDecimal)value$; break;
    case 9: gesuchsperiode = (ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'bezeichnungDE' field.
   * @return The value of the 'bezeichnungDE' field.
   */
  public java.lang.String getBezeichnungDE() {
    return bezeichnungDE;
  }


  /**
   * Sets the value of the 'bezeichnungDE' field.
   * @param value the value to set.
   */
  public void setBezeichnungDE(java.lang.String value) {
    this.bezeichnungDE = value;
  }

  /**
   * Gets the value of the 'bezeichnungFR' field.
   * @return The value of the 'bezeichnungFR' field.
   */
  public java.lang.String getBezeichnungFR() {
    return bezeichnungFR;
  }


  /**
   * Sets the value of the 'bezeichnungFR' field.
   * @param value the value to set.
   */
  public void setBezeichnungFR(java.lang.String value) {
    this.bezeichnungFR = value;
  }

  /**
   * Gets the value of the 'zeitVon' field.
   * @return The value of the 'zeitVon' field.
   */
  public long getZeitVon() {
    return zeitVon;
  }


  /**
   * Sets the value of the 'zeitVon' field.
   * @param value the value to set.
   */
  public void setZeitVon(long value) {
    this.zeitVon = value;
  }

  /**
   * Gets the value of the 'zeitBis' field.
   * @return The value of the 'zeitBis' field.
   */
  public long getZeitBis() {
    return zeitBis;
  }


  /**
   * Sets the value of the 'zeitBis' field.
   * @param value the value to set.
   */
  public void setZeitBis(long value) {
    this.zeitBis = value;
  }

  /**
   * Gets the value of the 'wochentage' field.
   * @return The value of the 'wochentage' field.
   */
  public java.util.List<java.lang.Integer> getWochentage() {
    return wochentage;
  }


  /**
   * Sets the value of the 'wochentage' field.
   * @param value the value to set.
   */
  public void setWochentage(java.util.List<java.lang.Integer> value) {
    this.wochentage = value;
  }

  /**
   * Gets the value of the 'intervall' field.
   * @return The value of the 'intervall' field.
   */
  public ch.dvbern.kibon.exchange.commons.types.Intervall getIntervall() {
    return intervall;
  }


  /**
   * Sets the value of the 'intervall' field.
   * @param value the value to set.
   */
  public void setIntervall(ch.dvbern.kibon.exchange.commons.types.Intervall value) {
    this.intervall = value;
  }

  /**
   * Gets the value of the 'padaegogischBetreut' field.
   * @return The value of the 'padaegogischBetreut' field.
   */
  public boolean getPadaegogischBetreut() {
    return padaegogischBetreut;
  }


  /**
   * Sets the value of the 'padaegogischBetreut' field.
   * @param value the value to set.
   */
  public void setPadaegogischBetreut(boolean value) {
    this.padaegogischBetreut = value;
  }

  /**
   * Gets the value of the 'verpflegungsKosten' field.
   * @return The value of the 'verpflegungsKosten' field.
   */
  public java.math.BigDecimal getVerpflegungsKosten() {
    return verpflegungsKosten;
  }


  /**
   * Sets the value of the 'verpflegungsKosten' field.
   * @param value the value to set.
   */
  public void setVerpflegungsKosten(java.math.BigDecimal value) {
    this.verpflegungsKosten = value;
  }

  /**
   * Gets the value of the 'gesuchsperiode' field.
   * @return The value of the 'gesuchsperiode' field.
   */
  public ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode getGesuchsperiode() {
    return gesuchsperiode;
  }


  /**
   * Sets the value of the 'gesuchsperiode' field.
   * @param value the value to set.
   */
  public void setGesuchsperiode(ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode value) {
    this.gesuchsperiode = value;
  }

  /**
   * Creates a new ModulDTO RecordBuilder.
   * @return A new ModulDTO RecordBuilder
   */
  public static ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder newBuilder() {
    return new ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder();
  }

  /**
   * Creates a new ModulDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ModulDTO RecordBuilder
   */
  public static ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder newBuilder(ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder other) {
    if (other == null) {
      return new ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder();
    } else {
      return new ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder(other);
    }
  }

  /**
   * Creates a new ModulDTO RecordBuilder by copying an existing ModulDTO instance.
   * @param other The existing instance to copy.
   * @return A new ModulDTO RecordBuilder
   */
  public static ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder newBuilder(ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO other) {
    if (other == null) {
      return new ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder();
    } else {
      return new ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for ModulDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ModulDTO>
    implements org.apache.avro.data.RecordBuilder<ModulDTO> {

    private java.lang.String id;
    private java.lang.String bezeichnungDE;
    private java.lang.String bezeichnungFR;
    private long zeitVon;
    private long zeitBis;
    private java.util.List<java.lang.Integer> wochentage;
    private ch.dvbern.kibon.exchange.commons.types.Intervall intervall;
    private boolean padaegogischBetreut;
    private java.math.BigDecimal verpflegungsKosten;
    private ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode gesuchsperiode;
    private ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode.Builder gesuchsperiodeBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.bezeichnungDE)) {
        this.bezeichnungDE = data().deepCopy(fields()[1].schema(), other.bezeichnungDE);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.bezeichnungFR)) {
        this.bezeichnungFR = data().deepCopy(fields()[2].schema(), other.bezeichnungFR);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.zeitVon)) {
        this.zeitVon = data().deepCopy(fields()[3].schema(), other.zeitVon);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.zeitBis)) {
        this.zeitBis = data().deepCopy(fields()[4].schema(), other.zeitBis);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.wochentage)) {
        this.wochentage = data().deepCopy(fields()[5].schema(), other.wochentage);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.intervall)) {
        this.intervall = data().deepCopy(fields()[6].schema(), other.intervall);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.padaegogischBetreut)) {
        this.padaegogischBetreut = data().deepCopy(fields()[7].schema(), other.padaegogischBetreut);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.verpflegungsKosten)) {
        this.verpflegungsKosten = data().deepCopy(fields()[8].schema(), other.verpflegungsKosten);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.gesuchsperiode)) {
        this.gesuchsperiode = data().deepCopy(fields()[9].schema(), other.gesuchsperiode);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (other.hasGesuchsperiodeBuilder()) {
        this.gesuchsperiodeBuilder = ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode.newBuilder(other.getGesuchsperiodeBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing ModulDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bezeichnungDE)) {
        this.bezeichnungDE = data().deepCopy(fields()[1].schema(), other.bezeichnungDE);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bezeichnungFR)) {
        this.bezeichnungFR = data().deepCopy(fields()[2].schema(), other.bezeichnungFR);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.zeitVon)) {
        this.zeitVon = data().deepCopy(fields()[3].schema(), other.zeitVon);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.zeitBis)) {
        this.zeitBis = data().deepCopy(fields()[4].schema(), other.zeitBis);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.wochentage)) {
        this.wochentage = data().deepCopy(fields()[5].schema(), other.wochentage);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.intervall)) {
        this.intervall = data().deepCopy(fields()[6].schema(), other.intervall);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.padaegogischBetreut)) {
        this.padaegogischBetreut = data().deepCopy(fields()[7].schema(), other.padaegogischBetreut);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.verpflegungsKosten)) {
        this.verpflegungsKosten = data().deepCopy(fields()[8].schema(), other.verpflegungsKosten);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.gesuchsperiode)) {
        this.gesuchsperiode = data().deepCopy(fields()[9].schema(), other.gesuchsperiode);
        fieldSetFlags()[9] = true;
      }
      this.gesuchsperiodeBuilder = null;
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bezeichnungDE' field.
      * @return The value.
      */
    public java.lang.String getBezeichnungDE() {
      return bezeichnungDE;
    }


    /**
      * Sets the value of the 'bezeichnungDE' field.
      * @param value The value of 'bezeichnungDE'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setBezeichnungDE(java.lang.String value) {
      validate(fields()[1], value);
      this.bezeichnungDE = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bezeichnungDE' field has been set.
      * @return True if the 'bezeichnungDE' field has been set, false otherwise.
      */
    public boolean hasBezeichnungDE() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bezeichnungDE' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearBezeichnungDE() {
      bezeichnungDE = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bezeichnungFR' field.
      * @return The value.
      */
    public java.lang.String getBezeichnungFR() {
      return bezeichnungFR;
    }


    /**
      * Sets the value of the 'bezeichnungFR' field.
      * @param value The value of 'bezeichnungFR'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setBezeichnungFR(java.lang.String value) {
      validate(fields()[2], value);
      this.bezeichnungFR = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bezeichnungFR' field has been set.
      * @return True if the 'bezeichnungFR' field has been set, false otherwise.
      */
    public boolean hasBezeichnungFR() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bezeichnungFR' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearBezeichnungFR() {
      bezeichnungFR = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'zeitVon' field.
      * @return The value.
      */
    public long getZeitVon() {
      return zeitVon;
    }


    /**
      * Sets the value of the 'zeitVon' field.
      * @param value The value of 'zeitVon'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setZeitVon(long value) {
      validate(fields()[3], value);
      this.zeitVon = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'zeitVon' field has been set.
      * @return True if the 'zeitVon' field has been set, false otherwise.
      */
    public boolean hasZeitVon() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'zeitVon' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearZeitVon() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'zeitBis' field.
      * @return The value.
      */
    public long getZeitBis() {
      return zeitBis;
    }


    /**
      * Sets the value of the 'zeitBis' field.
      * @param value The value of 'zeitBis'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setZeitBis(long value) {
      validate(fields()[4], value);
      this.zeitBis = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'zeitBis' field has been set.
      * @return True if the 'zeitBis' field has been set, false otherwise.
      */
    public boolean hasZeitBis() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'zeitBis' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearZeitBis() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'wochentage' field.
      * @return The value.
      */
    public java.util.List<java.lang.Integer> getWochentage() {
      return wochentage;
    }


    /**
      * Sets the value of the 'wochentage' field.
      * @param value The value of 'wochentage'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setWochentage(java.util.List<java.lang.Integer> value) {
      validate(fields()[5], value);
      this.wochentage = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'wochentage' field has been set.
      * @return True if the 'wochentage' field has been set, false otherwise.
      */
    public boolean hasWochentage() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'wochentage' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearWochentage() {
      wochentage = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'intervall' field.
      * @return The value.
      */
    public ch.dvbern.kibon.exchange.commons.types.Intervall getIntervall() {
      return intervall;
    }


    /**
      * Sets the value of the 'intervall' field.
      * @param value The value of 'intervall'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setIntervall(ch.dvbern.kibon.exchange.commons.types.Intervall value) {
      validate(fields()[6], value);
      this.intervall = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'intervall' field has been set.
      * @return True if the 'intervall' field has been set, false otherwise.
      */
    public boolean hasIntervall() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'intervall' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearIntervall() {
      intervall = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'padaegogischBetreut' field.
      * @return The value.
      */
    public boolean getPadaegogischBetreut() {
      return padaegogischBetreut;
    }


    /**
      * Sets the value of the 'padaegogischBetreut' field.
      * @param value The value of 'padaegogischBetreut'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setPadaegogischBetreut(boolean value) {
      validate(fields()[7], value);
      this.padaegogischBetreut = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'padaegogischBetreut' field has been set.
      * @return True if the 'padaegogischBetreut' field has been set, false otherwise.
      */
    public boolean hasPadaegogischBetreut() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'padaegogischBetreut' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearPadaegogischBetreut() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'verpflegungsKosten' field.
      * @return The value.
      */
    public java.math.BigDecimal getVerpflegungsKosten() {
      return verpflegungsKosten;
    }


    /**
      * Sets the value of the 'verpflegungsKosten' field.
      * @param value The value of 'verpflegungsKosten'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setVerpflegungsKosten(java.math.BigDecimal value) {
      validate(fields()[8], value);
      this.verpflegungsKosten = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'verpflegungsKosten' field has been set.
      * @return True if the 'verpflegungsKosten' field has been set, false otherwise.
      */
    public boolean hasVerpflegungsKosten() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'verpflegungsKosten' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearVerpflegungsKosten() {
      verpflegungsKosten = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'gesuchsperiode' field.
      * @return The value.
      */
    public ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode getGesuchsperiode() {
      return gesuchsperiode;
    }


    /**
      * Sets the value of the 'gesuchsperiode' field.
      * @param value The value of 'gesuchsperiode'.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setGesuchsperiode(ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode value) {
      validate(fields()[9], value);
      this.gesuchsperiodeBuilder = null;
      this.gesuchsperiode = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'gesuchsperiode' field has been set.
      * @return True if the 'gesuchsperiode' field has been set, false otherwise.
      */
    public boolean hasGesuchsperiode() {
      return fieldSetFlags()[9];
    }

    /**
     * Gets the Builder instance for the 'gesuchsperiode' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode.Builder getGesuchsperiodeBuilder() {
      if (gesuchsperiodeBuilder == null) {
        if (hasGesuchsperiode()) {
          setGesuchsperiodeBuilder(ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode.newBuilder(gesuchsperiode));
        } else {
          setGesuchsperiodeBuilder(ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode.newBuilder());
        }
      }
      return gesuchsperiodeBuilder;
    }

    /**
     * Sets the Builder instance for the 'gesuchsperiode' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder setGesuchsperiodeBuilder(ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode.Builder value) {
      clearGesuchsperiode();
      gesuchsperiodeBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'gesuchsperiode' field has an active Builder instance
     * @return True if the 'gesuchsperiode' field has an active Builder instance
     */
    public boolean hasGesuchsperiodeBuilder() {
      return gesuchsperiodeBuilder != null;
    }

    /**
      * Clears the value of the 'gesuchsperiode' field.
      * @return This builder.
      */
    public ch.dvbern.kibon.exchange.commons.tagesschulen.ModulDTO.Builder clearGesuchsperiode() {
      gesuchsperiode = null;
      gesuchsperiodeBuilder = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ModulDTO build() {
      try {
        ModulDTO record = new ModulDTO();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.bezeichnungDE = fieldSetFlags()[1] ? this.bezeichnungDE : (java.lang.String) defaultValue(fields()[1]);
        record.bezeichnungFR = fieldSetFlags()[2] ? this.bezeichnungFR : (java.lang.String) defaultValue(fields()[2]);
        record.zeitVon = fieldSetFlags()[3] ? this.zeitVon : (java.lang.Long) defaultValue(fields()[3]);
        record.zeitBis = fieldSetFlags()[4] ? this.zeitBis : (java.lang.Long) defaultValue(fields()[4]);
        record.wochentage = fieldSetFlags()[5] ? this.wochentage : (java.util.List<java.lang.Integer>) defaultValue(fields()[5]);
        record.intervall = fieldSetFlags()[6] ? this.intervall : (ch.dvbern.kibon.exchange.commons.types.Intervall) defaultValue(fields()[6]);
        record.padaegogischBetreut = fieldSetFlags()[7] ? this.padaegogischBetreut : (java.lang.Boolean) defaultValue(fields()[7]);
        record.verpflegungsKosten = fieldSetFlags()[8] ? this.verpflegungsKosten : (java.math.BigDecimal) defaultValue(fields()[8]);
        if (gesuchsperiodeBuilder != null) {
          try {
            record.gesuchsperiode = this.gesuchsperiodeBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("gesuchsperiode"));
            throw e;
          }
        } else {
          record.gesuchsperiode = fieldSetFlags()[9] ? this.gesuchsperiode : (ch.dvbern.kibon.exchange.commons.types.Gesuchsperiode) defaultValue(fields()[9]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ModulDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<ModulDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ModulDTO>
    READER$ = (org.apache.avro.io.DatumReader<ModulDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










