/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ch.dvbern.kibon.exchange.commons.tagesschulen;
@org.apache.avro.specific.AvroGenerated
public enum TagesschuleAnmeldungStatus implements org.apache.avro.generic.GenericEnumSymbol<TagesschuleAnmeldungStatus> {
  SCHULAMT_ANMELDUNG_ERFASST, SCHULAMT_ANMELDUNG_AUSGELOEST, SCHULAMT_MODULE_AKZEPTIERT, SCHULAMT_ANMELDUNG_UEBERNOMMEN, SCHULAMT_ANMELDUNG_ABGELEHNT, SCHULAMT_FALSCHE_INSTITUTION, SCHULAMT_ANMELDUNG_STORNIERT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TagesschuleAnmeldungStatus\",\"namespace\":\"ch.dvbern.kibon.exchange.commons.tagesschulen\",\"symbols\":[\"SCHULAMT_ANMELDUNG_ERFASST\",\"SCHULAMT_ANMELDUNG_AUSGELOEST\",\"SCHULAMT_MODULE_AKZEPTIERT\",\"SCHULAMT_ANMELDUNG_UEBERNOMMEN\",\"SCHULAMT_ANMELDUNG_ABGELEHNT\",\"SCHULAMT_FALSCHE_INSTITUTION\",\"SCHULAMT_ANMELDUNG_STORNIERT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
